In [33]:
import joblib

svm_model = joblib.load('svm_model.pkl')
tf = joblib.load('tfidf_vectorizer.pkl')

In [34]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,accuracy_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

In [35]:
df=pd.read_csv('test_data_solution.txt',sep=':::',names=['ID','TITLE','GENRE','DESCRIPTION'])
df1=pd.read_csv('test_data.txt',sep=':::',names=['ID','TITLE','DESCRIPTION'])

C:\Users\ASUS\AppData\Local\Temp\ipykernel_23768\3217979741.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df=pd.read_csv('test_data_solution.txt',sep=':::',names=['ID','TITLE','GENRE','DESCRIPTION'])
C:\Users\ASUS\AppData\Local\Temp\ipykernel_23768\3217979741.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df1=pd.read_csv('test_data.txt',sep=':::',names=['ID','TITLE','DESCRIPTION'])

In [36]:
df.head()

,ID,TITLE,GENRE,DESCRIPTION
0,1,Edgar's Lunch (1998),thriller,"L.R. Brane loves his life - his car, his apar..."
1,2,La guerra de papá (1977),comedy,"Spain, March 1964: Quico is a very naughty ch..."
2,3,Off the Beaten Track (2010),documentary,One year in the life of Albin and his family ...
3,4,Meu Amigo Hindu (2015),drama,"His father has died, he hasn't spoken with hi..."
4,5,Er nu zhai (1955),drama,Before he was known internationally as a mart...

In [37]:
df1.head()

,ID,TITLE,DESCRIPTION
0,1,Edgar's Lunch (1998),"L.R. Brane loves his life - his car, his apar..."
1,2,La guerra de papá (1977),"Spain, March 1964: Quico is a very naughty ch..."
2,3,Off the Beaten Track (2010),One year in the life of Albin and his family ...
3,4,Meu Amigo Hindu (2015),"His father has died, he hasn't spoken with hi..."
4,5,Er nu zhai (1955),Before he was known internationally as a mart...

In [38]:
df1['DESCRIPTION_CLEAN'] = df1['DESCRIPTION'].str.replace('[^\w\s]','').str.lower()

<>:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
<>:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
C:\Users\ASUS\AppData\Local\Temp\ipykernel_23768\2426034144.py:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
  df1['DESCRIPTION_CLEAN'] = df1['DESCRIPTION'].str.replace('[^\w\s]','').str.lower()

In [39]:
svm_model = joblib.load('svm_model.pkl')

In [40]:
X=tf.transform(df1['DESCRIPTION_CLEAN'])
ytrue=df['GENRE']

In [41]:
ypred = svm_model.predict(X)
acc = accuracy_score(ytrue, ypred)
print(f"SVM — Accuracy: {acc*100:.2f}%")
print(classification_report(ytrue, ypred))

SVM — Accuracy: 55.32%
               precision    recall  f1-score   support

      action        0.32      0.44      0.37      1314
       adult        0.44      0.56      0.50       590
   adventure        0.30      0.29      0.29       775
   animation        0.25      0.24      0.25       498
   biography        0.03      0.02      0.02       264
      comedy        0.58      0.54      0.56      7446
       crime        0.17      0.19      0.18       505
 documentary        0.74      0.77      0.75     13096
       drama        0.65      0.56      0.60     13612
      family        0.21      0.25      0.23       783
     fantasy        0.17      0.17      0.17       322
   game-show        0.66      0.71      0.68       193
     history        0.05      0.03      0.04       243
      horror        0.52      0.69      0.59      2204
       music        0.48      0.69      0.57       731
     musical        0.13      0.12      0.12       276
     mystery        0.13      0.11      0.12       318
        news        0.31      0.22      0.26       181
  reality-tv        0.32      0.39      0.35       883
     romance        0.16      0.22      0.19       672
      sci-fi        0.34      0.46      0.39       646
       short        0.45      0.37      0.41      5072
       sport        0.40      0.57      0.47       431
   talk-show        0.33      0.40      0.36       391
    thriller        0.24      0.27      0.25      1590
         war        0.30      0.36      0.33       132
     western        0.70      0.89      0.79      1032

     accuracy                           0.55     54200
    macro avg       0.35      0.39      0.36     54200
 weighted avg       0.56      0.55      0.55     54200